import Head from 'next/head'
import Weather from '../components/Weather'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Weather/>
      <Footer/>

    </div>
  )
}
